// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMat.WebAPI.Data;

namespace ProMat.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201031065528_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("ProMat.WebAPI.Model.DisqualifiedQueue", b =>
                {
                    b.Property<int>("DisqualifiedQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateBorn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJobEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevSituation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Situation")
                        .HasColumnType("TEXT");

                    b.HasKey("DisqualifiedQueueId");

                    b.ToTable("DisqualifiedQueues");
                });

            modelBuilder.Entity("ProMat.WebAPI.Model.QualifiedQueue", b =>
                {
                    b.Property<int>("QualifiedQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateBorn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJobEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevSituation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .HasColumnType("TEXT");

                    b.HasKey("QualifiedQueueId");

                    b.ToTable("QualifiedQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
