// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProMat.WebAPI.Data;

namespace ProMat.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201118021510_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("ProMat.WebAPI.Model.Attendant", b =>
                {
                    b.Property<string>("AttendantId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("AttendantId");

                    b.ToTable("Attendants");
                });

            modelBuilder.Entity("ProMat.WebAPI.Model.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProMat.WebAPI.Model.DisqualifiedLead", b =>
                {
                    b.Property<int>("DisqualifiedLeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendantID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateBorn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateJobEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevSituation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegJobReceive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .HasColumnType("TEXT");

                    b.HasKey("DisqualifiedLeadId");

                    b.ToTable("DisqualifiedLeads");
                });

            modelBuilder.Entity("ProMat.WebAPI.Model.QualifiedLead", b =>
                {
                    b.Property<int>("QualifiedLeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendantID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateBorn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateJobEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevSituation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegJobReceive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .HasColumnType("TEXT");

                    b.HasKey("QualifiedLeadId");

                    b.ToTable("QualifiedLeads");
                });
#pragma warning restore 612, 618
        }
    }
}
